version: 0.2

phases:
  install:
    commands:
      - python2.7 -m amazon_linux_extras enable docker
      - yum install --assumeyes amazon-ecr-credential-helper

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Building and pushing the docker image ...
      - IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "{\"Tag\":\"${IMAGE_TAG}\"}" | jq . > parameters.json
      - echo "$IMAGE_REPO_NAME:$IMAGE_TAG"

      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG src
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      

artifacts:
  discard-paths: yes
  files:
    - infra/cf-template.yaml
    - infra/cf-template.config
    - parameters.json
